on:
  workflow_call:
    inputs:
      configuration:
        required: false
        type: string
        default: $(echo "INJECTED")

jobs:
  vulnerable:
    name: a vulnerable workflow
    runs-on: ubuntu-latest
    env:
      configuration: $(echo "INJECTED")
    steps:
      - name: echo configuration "${configuration}"
        run: echo Hello "${configuration}"

